version: "3.9"
services:
  app:
    build: .
    container_name: node_app_test
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Datos2025
      DB_NAME: Prueba01
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_test
    environment:
      MYSQL_ROOT_PASSWORD: Datos2025
      MYSQL_DATABASE: Prueba01
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data:
